//
// Created by ziyan on 1/18/20.
//

#ifndef MYNETWORK_LIBRARY_DPDK_MACRO_H
#define MYNETWORK_LIBRARY_DPDK_MACRO_H


#define RX_RING_SIZE 1024
#define TX_RING_SIZE 0
#define NUM_MBUFS 8191
#define MBUF_CACHE_SIZE 250

#endif //MYNETWORK_LIBRARY_DPDK_MACRO_H
